baseURL = "https://clipperhouse.com"
languageCode = "en-us"
title = "clipperhouse.com"
theme = "blank"
summaryLength = 12
disableHugoGeneratorInject = true

[params]
  author = "Matt Sherman"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "friendly"
lineNos = false
lineNumbersInTable = false
noClasses = false
