baseURL = "https://clipperhouse.com"
languageCode = "en-us"
title = "clipperhouse.com"
theme = "hugo-paper"
summaryLength = 12

[params]
  author = "Matt Sherman"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"

[markup.goldmark.renderer]
unsafe = true